### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by RPagels** [johannesegger/SenseHatNet#3]
Hi,

I'm running your example on a Raspberry Pi running Dot Net Core 2.2.  I'm using your example: Progam.cs and get an an invalid argument when calling this line:  Sense.Led.LedMatrix.ShowMessage("Welcome");

![image](https://user-images.githubusercontent.com/20913744/52182919-80da9400-27d0-11e9-875a-7568a9a71985.png)

Any thoughts on how I can get around this?

BTW, the call to TestRTIMULib(); works great and reports back the Humidity & Temperature.

Thank you,

Randy

**Comment by johannesegger** [comment]
Thanks for reporting this.

Looks like it's the same as #1. Can you please try [the suggestions](https://github.com/johannesegger/SenseHatNet/issues/2#issuecomment-457942104) there? Also can you check if it works with the original python library?

**Comment by johannesegger** [comment]
Please note that there's an error in the linked suggestion: Replace `/etc/sys/graphics/fb*/name` with `/sys/class/graphics/fb*/name`.

**Comment by akacprzak** [comment]
@johannesegger

I the same problem using your lib, but without docker. 
I reported that issue and got fix for that on:
https://github.com/dotnet/coreclr/issues/22787

Do you think you could update your code for that fix ? 
It could be helpful for others with same issue.

**Comment by johannesegger** [comment]
Thanks for reporting this in the coreclr repo. Please try SenseHatNet 0.0.4

**Comment by RPagels** [comment]
Thank you for the update. Version 0.0.4 worked great with DotNetCore 2.2. Awesome!
